name: SevenZipBackup
version: ${project.version}
api-version: 0.0.1
description: Uploads backups to Google Drive/OneDrive or by (S)FTP
main: Windsor.SevenZipBackup.plugin.SevenZipBackup
author: WindsorMacmillan
commands:
  7zbackup:
    description: View all SevenZipBackup commands
    usage: /7zbackup