name: SevenZipBackup CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'SevenZipBackup/**'
  pull_request:
    paths:
      - 'SevenZipBackup/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml -B package --file $GITHUB_WORKSPACE/SevenZipBackup/pom.xml
      env:
        USER_NAME: ${{ secrets.CRED_SERVER_USERNAME }}
        ACCESS_TOKEN: ${{ secrets.CRED_SERVER_PASSWORD }}
    - uses: actions/upload-artifact@v4
      with:
        name: SevenZipBackup.jar
        path: SevenZipBackup/target/SevenZipBackup.jar
